Add patch to include missing libxml/SAX.h header
Fix: error: 'getLineNumber' was not declared in this scope

Note that that getLineNumber and getColumnNumber are deprecated.
Should be replaced by xmlSAX2GetLineNumber and xmlSAX2GetColumnNumber
(libxml/SAX2.h is included)